### ISSUE TITLE
Default proxy port

### ISSUE THREAD

**Issue by mauriciogeneroso** [requestly/requestly-desktop-app#6]
Hi, I'm new on the desktop app for Mac and I didn't find how to change the default port.

It starts on port 8080 and I'd like to change to something else, is this feature supported?

In case it is not supported, I would recommend to include this option, and usually port 8080 is really common for Java Spring applications, it would be useful for the default port to be something else (Fiddler uses 8888 as default).

Thank you.

**Comment by wrongsahil** [comment]
Hey @mauriciogeneroso 
We don't support changing the default port right now, but we have this on our bucket list. We'll keep you posted here when this is available.

Until then, when any other server runs on `8080`, the proxy port automatically changes to a different port. This might help you to run Requestly with another Java Spring Server.

**Comment by mauriciogeneroso** [comment]
@wrongsahil thank you.

**Comment by nsrCodes** [comment]
It is now possible to change the proxy part after [version 1.4.19](https://github.com/requestly/requestly-desktop-app/releases/tag/v1.4.19) 

The default port has also been changed to something less common
