### ISSUE TITLE
bug: Unable to download Requestly Desktop for Apple Silicon - Page getting timed out

### ISSUE THREAD

**Issue by bkannanv1** [requestly/requestly-desktop-app#64]
## Prerequisites

N/A

- [ ] Using the latest version of Requestly 

## Expected Behavior

Should be able to download the Application

## Current Behavior

The page is getting timed out

## Steps to Reproduce

1. Navigate to https://requestly.io/downloads/
3. Hit the download link for Apple silicon

![image](https://github.com/requestly/requestly/assets/128489265/3cac408c-ce45-41f7-8385-ce8eb5c01b84)

## Possible Solution (Not obligatory)

The file hosting sever should be checked and fixed.

## Context

Tried on different browsers, and different machines. The issue is from the server side.

## Your Environment

Apple Silicon

**Comment by nsrCodes** [comment]
Thank you @bkannanv1 for pointing this out, we will fix the download link there ASAP. Meanwhile you can download the latest release from here - https://github.com/requestly/requestly-desktop-app/releases

**Comment by sagarsoni7** [comment]
The links have been fixed. Please feel free to reopen in case if the issue appears again.
